# practice

In [1]:
import torch

In [3]:
a = torch.ones(size=[3, 3])
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [7]:
b = torch.randint(low=2, high=8, size=(3, 2), dtype=torch.float)
b

tensor([[7., 7.],
        [5., 3.],
        [7., 6.]])

In [8]:
a @ b

tensor([[19., 16.],
        [19., 16.],
        [19., 16.]])

In [11]:
c = torch.tril(a)
c

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])

In [12]:
c @ b

tensor([[ 7.,  7.],
        [12., 10.],
        [19., 16.]])